### Регистрация выпускника
POST http://localhost:4000/api/auth/registration
Content-Type: application/json

{
  "email": "student@example.com",
  "password": "password123",
  "first_name": "Иван",
  "last_name": "Иванов",
  "role": "graduate"
}

### Вход в систему
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "student@example.com",
  "password": "password123"
}

### Получить профиль (нужен токен!)
GET http://localhost:4000/api/graduates/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImdyYWR1YXRlIiwiaWF0IjoxNzYzNjQ1MzMyLCJleHAiOjE3NjM3MzE3MzJ9.LIAy5jrn-bDj1BhYlnqh4QF0M1gBsAVIGoHydKvXwrk

### Обновить профиль
PUT http://localhost:4000/api/graduates/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImdyYWR1YXRlIiwiaWF0IjoxNzYzNjQ1MzMyLCJleHAiOjE3NjM3MzE3MzJ9.LIAy5jrn-bDj1BhYlnqh4QF0M1gBsAVIGoHydKvXwrk
Content-Type: application/json

{
  "first_name": "Александр",
  "last_name": "Белянчиков",
  "middle_name": "Сергеевич",
  "graduation_year": 2025,
  "portfolio_link": "https://github.com/kellocare"
}

### Получить список компаний
GET http://127.0.0.1:4000/api/dict/companies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImdyYWR1YXRlIiwiaWF0IjoxNzYzNjQ1MzMyLCJleHAiOjE3NjM3MzE3MzJ9.LIAy5jrn-bDj1BhYlnqh4QF0M1gBsAVIGoHydKvXwrk

### Добавить запись о работе (Поменяй company_id на реальный, например 1)
POST http://127.0.0.1:4000/api/employment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImdyYWR1YXRlIiwiaWF0IjoxNzYzNjQ1MzMyLCJleHAiOjE3NjM3MzE3MzJ9.LIAy5jrn-bDj1BhYlnqh4QF0M1gBsAVIGoHydKvXwrk
Content-Type: application/json

{
  "company_id": 1,
  "position_title": "Junior Developer",
  "start_date": "2025-01-10",
  "salary_amount": 80000,
  "is_current": true
}

### Посмотреть мои работы
GET http://127.0.0.1:4000/api/employment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImdyYWR1YXRlIiwiaWF0IjoxNzYzNjQ1MzMyLCJleHAiOjE3NjM3MzE3MzJ9.LIAy5jrn-bDj1BhYlnqh4QF0M1gBsAVIGoHydKvXwrk